language: generic
sudo: false

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - env: Python=3.7 THREDDS="test"
    - env: Python=3.7 THREDDS="dev"
    - env: Python=3.7 THREDDS="jetstream"
  exclude:
    - os: osx
      env: Python=3.7 THREDDS="test"
    - os: osx
      env: Python=3.7 THREDDS="dev"
    - os: osx
      env: Python=3.7 THREDDS="jetstream"

env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
  matrix:
    - Python=3.6 THREDDS="main"
    - Python=3.7 THREDDS="main"
    - Python=3.7 THREDDS="test"
    - Python=3.7 THREDDS="dev"
    - Python=3.7 THREDDS="jetstream"


before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      export CONDA_OS_NAME="MacOSX";
    else
      export CONDA_OS_NAME="Linux";
    fi;
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${CONDA_OS_NAME}-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $MINICONDA_DIR
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - sed -i -e "s/python=3/python=$Python/" environment.yml;

install:
  - conda env create -q -f environment.yml
  - source activate gallery
  - conda install -c conda-forge flake8 flake8-quotes flake8-mutable flake8-pep3101 flake8-comprehensions flake8-builtins flake8-import-order
  - conda list

script:
  - if [[ $THREDDS != "main" ]]; then
       python thredds_test_converter.py $THREDDS;
    fi;
  - flake8 examples metpy_mondays
  - pushd website
  - travis_retry make html
  - popd

before_deploy:
  # Remove unused, unminified javascript from sphinx
  - touch website/build/html/.nojekyll;
  - rm -f website/build/html/_static/jquery-*.js;
  - rm -f website/build/html/_static/underscore-*.js;
  - rm -f website/build/html/.buildinfo

deploy:
  provider: script
  script: deploy/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    os: linux
    condition: $Python == '3.7'
