 name: gallery
 channels:
   - conda-forge
 dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - metpy
   - siphon
   - sphinx
   - sphinx-gallery
   - sphinx_rtd_theme
   - xarray
   - boto3
   - botocore
   - pint
   - pip:
       - sphinx-markdown-tables
